name: "devsecops-crud-frontend"
version: "0.0.0"
environment: "dev"
validation:
  enabled: true
buildTests:
  enabled: false
qualityAssurance:
  enabled: false
build:
  enabled: false
delivery:
  enabled: false
deploy:
  enabled: false
deployTests:
  enabled: false
monitoring:
  enabled: false
observability:
  enabled: false
feedback:
  enabled: false